// Generated by tools/gen_glnull.py from glcore.h - do not edit.
#include "graphics/glcore.h"

extern "C" {

static void CODEGEN_FUNCPTR null_glBlendFunc(GLenum, GLenum) {  }
static void CODEGEN_FUNCPTR null_glClear(GLbitfield) {  }
static void CODEGEN_FUNCPTR null_glClearColor(GLfloat, GLfloat, GLfloat, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glClearDepth(GLdouble) {  }
static void CODEGEN_FUNCPTR null_glClearStencil(GLint) {  }
static void CODEGEN_FUNCPTR null_glColorMask(GLboolean, GLboolean, GLboolean, GLboolean) {  }
static void CODEGEN_FUNCPTR null_glCullFace(GLenum) {  }
static void CODEGEN_FUNCPTR null_glDepthFunc(GLenum) {  }
static void CODEGEN_FUNCPTR null_glDepthMask(GLboolean) {  }
static void CODEGEN_FUNCPTR null_glDepthRange(GLdouble, GLdouble) {  }
static void CODEGEN_FUNCPTR null_glDisable(GLenum) {  }
static void CODEGEN_FUNCPTR null_glDrawBuffer(GLenum) {  }
static void CODEGEN_FUNCPTR null_glEnable(GLenum) {  }
static void CODEGEN_FUNCPTR null_glFinish(void) {  }
static void CODEGEN_FUNCPTR null_glFlush(void) {  }
static void CODEGEN_FUNCPTR null_glFrontFace(GLenum) {  }
static void CODEGEN_FUNCPTR null_glGetBooleanv(GLenum, GLboolean *) {  }
static void CODEGEN_FUNCPTR null_glGetDoublev(GLenum, GLdouble *) {  }
static GLenum CODEGEN_FUNCPTR null_glGetError(void) { return 0; }
static void CODEGEN_FUNCPTR null_glGetFloatv(GLenum, GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glGetIntegerv(GLenum, GLint *) {  }
static const GLubyte * CODEGEN_FUNCPTR null_glGetString(GLenum) { static const GLubyte s[] = ""; return s; }
static void CODEGEN_FUNCPTR null_glGetTexImage(GLenum, GLint, GLenum, GLenum, GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glGetTexLevelParameterfv(GLenum, GLint, GLenum, GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glGetTexLevelParameteriv(GLenum, GLint, GLenum, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetTexParameterfv(GLenum, GLenum, GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glGetTexParameteriv(GLenum, GLenum, GLint *) {  }
static void CODEGEN_FUNCPTR null_glHint(GLenum, GLenum) {  }
static GLboolean CODEGEN_FUNCPTR null_glIsEnabled(GLenum) { return 0; }
static void CODEGEN_FUNCPTR null_glLineWidth(GLfloat) {  }
static void CODEGEN_FUNCPTR null_glLogicOp(GLenum) {  }
static void CODEGEN_FUNCPTR null_glPixelStoref(GLenum, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glPixelStorei(GLenum, GLint) {  }
static void CODEGEN_FUNCPTR null_glPointSize(GLfloat) {  }
static void CODEGEN_FUNCPTR null_glPolygonMode(GLenum, GLenum) {  }
static void CODEGEN_FUNCPTR null_glReadBuffer(GLenum) {  }
static void CODEGEN_FUNCPTR null_glReadPixels(GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glScissor(GLint, GLint, GLsizei, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glStencilFunc(GLenum, GLint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glStencilMask(GLuint) {  }
static void CODEGEN_FUNCPTR null_glStencilOp(GLenum, GLenum, GLenum) {  }
static void CODEGEN_FUNCPTR null_glTexImage1D(GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glTexImage2D(GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glTexParameterf(GLenum, GLenum, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glTexParameterfv(GLenum, GLenum, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glTexParameteri(GLenum, GLenum, GLint) {  }
static void CODEGEN_FUNCPTR null_glTexParameteriv(GLenum, GLenum, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glViewport(GLint, GLint, GLsizei, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glBindTexture(GLenum, GLuint) {  }
static void CODEGEN_FUNCPTR null_glCopyTexImage1D(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint) {  }
static void CODEGEN_FUNCPTR null_glCopyTexImage2D(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint) {  }
static void CODEGEN_FUNCPTR null_glCopyTexSubImage1D(GLenum, GLint, GLint, GLint, GLint, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glCopyTexSubImage2D(GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glDeleteTextures(GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glDrawArrays(GLenum, GLint, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glDrawElements(GLenum, GLsizei, GLenum, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glGenTextures(GLsizei, GLuint *) {  }
static GLboolean CODEGEN_FUNCPTR null_glIsTexture(GLuint) { return 0; }
static void CODEGEN_FUNCPTR null_glPolygonOffset(GLfloat, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glTexSubImage1D(GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glTexSubImage2D(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glBlendColor(GLfloat, GLfloat, GLfloat, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glBlendEquation(GLenum) {  }
static void CODEGEN_FUNCPTR null_glCopyTexSubImage3D(GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glDrawRangeElements(GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glTexImage3D(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glTexSubImage3D(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glActiveTexture(GLenum) {  }
static void CODEGEN_FUNCPTR null_glCompressedTexImage1D(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glCompressedTexImage2D(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glCompressedTexImage3D(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glCompressedTexSubImage1D(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glCompressedTexSubImage2D(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glCompressedTexSubImage3D(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glGetCompressedTexImage(GLenum, GLint, GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glSampleCoverage(GLfloat, GLboolean) {  }
static void CODEGEN_FUNCPTR null_glBlendFuncSeparate(GLenum, GLenum, GLenum, GLenum) {  }
static void CODEGEN_FUNCPTR null_glMultiDrawArrays(GLenum, const GLint *, const GLsizei *, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glMultiDrawElements(GLenum, const GLsizei *, GLenum, const GLvoid *const*, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glPointParameterf(GLenum, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glPointParameterfv(GLenum, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glPointParameteri(GLenum, GLint) {  }
static void CODEGEN_FUNCPTR null_glPointParameteriv(GLenum, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glBeginQuery(GLenum, GLuint) {  }
static void CODEGEN_FUNCPTR null_glBindBuffer(GLenum, GLuint) {  }
static void CODEGEN_FUNCPTR null_glBufferData(GLenum, GLsizeiptr, const GLvoid *, GLenum) {  }
static void CODEGEN_FUNCPTR null_glBufferSubData(GLenum, GLintptr, GLsizeiptr, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glDeleteBuffers(GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glDeleteQueries(GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glEndQuery(GLenum) {  }
static void CODEGEN_FUNCPTR null_glGenBuffers(GLsizei, GLuint *) {  }
static void CODEGEN_FUNCPTR null_glGenQueries(GLsizei, GLuint *) {  }
static void CODEGEN_FUNCPTR null_glGetBufferParameteriv(GLenum, GLenum, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetBufferPointerv(GLenum, GLenum, GLvoid **) {  }
static void CODEGEN_FUNCPTR null_glGetBufferSubData(GLenum, GLintptr, GLsizeiptr, GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glGetQueryObjectiv(GLuint, GLenum, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetQueryObjectuiv(GLuint, GLenum, GLuint *) {  }
static void CODEGEN_FUNCPTR null_glGetQueryiv(GLenum, GLenum, GLint *) {  }
static GLboolean CODEGEN_FUNCPTR null_glIsBuffer(GLuint) { return 0; }
static GLboolean CODEGEN_FUNCPTR null_glIsQuery(GLuint) { return 0; }
static void * CODEGEN_FUNCPTR null_glMapBuffer(GLenum, GLenum) { return 0; }
static GLboolean CODEGEN_FUNCPTR null_glUnmapBuffer(GLenum) { return 0; }
static void CODEGEN_FUNCPTR null_glAttachShader(GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glBindAttribLocation(GLuint, GLuint, const GLchar *) {  }
static void CODEGEN_FUNCPTR null_glBlendEquationSeparate(GLenum, GLenum) {  }
static void CODEGEN_FUNCPTR null_glCompileShader(GLuint) {  }
static GLuint CODEGEN_FUNCPTR null_glCreateProgram(void) { return 0; }
static GLuint CODEGEN_FUNCPTR null_glCreateShader(GLenum) { return 0; }
static void CODEGEN_FUNCPTR null_glDeleteProgram(GLuint) {  }
static void CODEGEN_FUNCPTR null_glDeleteShader(GLuint) {  }
static void CODEGEN_FUNCPTR null_glDetachShader(GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glDisableVertexAttribArray(GLuint) {  }
static void CODEGEN_FUNCPTR null_glDrawBuffers(GLsizei, const GLenum *) {  }
static void CODEGEN_FUNCPTR null_glEnableVertexAttribArray(GLuint) {  }
static void CODEGEN_FUNCPTR null_glGetActiveAttrib(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *) {  }
static void CODEGEN_FUNCPTR null_glGetActiveUniform(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *) {  }
static void CODEGEN_FUNCPTR null_glGetAttachedShaders(GLuint, GLsizei, GLsizei *, GLuint *) {  }
static GLint CODEGEN_FUNCPTR null_glGetAttribLocation(GLuint, const GLchar *) { return -1; }
static void CODEGEN_FUNCPTR null_glGetProgramInfoLog(GLuint, GLsizei, GLsizei *, GLchar *) {  }
static void CODEGEN_FUNCPTR null_glGetProgramiv(GLuint, GLenum, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetShaderInfoLog(GLuint, GLsizei, GLsizei *, GLchar *) {  }
static void CODEGEN_FUNCPTR null_glGetShaderSource(GLuint, GLsizei, GLsizei *, GLchar *) {  }
static void CODEGEN_FUNCPTR null_glGetShaderiv(GLuint, GLenum, GLint *) {  }
static GLint CODEGEN_FUNCPTR null_glGetUniformLocation(GLuint, const GLchar *) { return -1; }
static void CODEGEN_FUNCPTR null_glGetUniformfv(GLuint, GLint, GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glGetUniformiv(GLuint, GLint, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetVertexAttribPointerv(GLuint, GLenum, GLvoid **) {  }
static void CODEGEN_FUNCPTR null_glGetVertexAttribdv(GLuint, GLenum, GLdouble *) {  }
static void CODEGEN_FUNCPTR null_glGetVertexAttribfv(GLuint, GLenum, GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glGetVertexAttribiv(GLuint, GLenum, GLint *) {  }
static GLboolean CODEGEN_FUNCPTR null_glIsProgram(GLuint) { return 0; }
static GLboolean CODEGEN_FUNCPTR null_glIsShader(GLuint) { return 0; }
static void CODEGEN_FUNCPTR null_glLinkProgram(GLuint) {  }
static void CODEGEN_FUNCPTR null_glShaderSource(GLuint, GLsizei, const GLchar *const*, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glStencilFuncSeparate(GLenum, GLenum, GLint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glStencilMaskSeparate(GLenum, GLuint) {  }
static void CODEGEN_FUNCPTR null_glStencilOpSeparate(GLenum, GLenum, GLenum, GLenum) {  }
static void CODEGEN_FUNCPTR null_glUniform1f(GLint, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glUniform1fv(GLint, GLsizei, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniform1i(GLint, GLint) {  }
static void CODEGEN_FUNCPTR null_glUniform1iv(GLint, GLsizei, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glUniform2f(GLint, GLfloat, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glUniform2fv(GLint, GLsizei, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniform2i(GLint, GLint, GLint) {  }
static void CODEGEN_FUNCPTR null_glUniform2iv(GLint, GLsizei, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glUniform3f(GLint, GLfloat, GLfloat, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glUniform3fv(GLint, GLsizei, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniform3i(GLint, GLint, GLint, GLint) {  }
static void CODEGEN_FUNCPTR null_glUniform3iv(GLint, GLsizei, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glUniform4f(GLint, GLfloat, GLfloat, GLfloat, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glUniform4fv(GLint, GLsizei, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniform4i(GLint, GLint, GLint, GLint, GLint) {  }
static void CODEGEN_FUNCPTR null_glUniform4iv(GLint, GLsizei, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glUniformMatrix2fv(GLint, GLsizei, GLboolean, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniformMatrix3fv(GLint, GLsizei, GLboolean, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniformMatrix4fv(GLint, GLsizei, GLboolean, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUseProgram(GLuint) {  }
static void CODEGEN_FUNCPTR null_glValidateProgram(GLuint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib1d(GLuint, GLdouble) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib1dv(GLuint, const GLdouble *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib1f(GLuint, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib1fv(GLuint, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib1s(GLuint, GLshort) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib1sv(GLuint, const GLshort *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib2d(GLuint, GLdouble, GLdouble) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib2dv(GLuint, const GLdouble *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib2f(GLuint, GLfloat, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib2fv(GLuint, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib2s(GLuint, GLshort, GLshort) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib2sv(GLuint, const GLshort *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib3d(GLuint, GLdouble, GLdouble, GLdouble) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib3dv(GLuint, const GLdouble *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib3f(GLuint, GLfloat, GLfloat, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib3fv(GLuint, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib3s(GLuint, GLshort, GLshort, GLshort) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib3sv(GLuint, const GLshort *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4Nbv(GLuint, const GLbyte *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4Niv(GLuint, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4Nsv(GLuint, const GLshort *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4Nub(GLuint, GLubyte, GLubyte, GLubyte, GLubyte) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4Nubv(GLuint, const GLubyte *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4Nuiv(GLuint, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4Nusv(GLuint, const GLushort *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4bv(GLuint, const GLbyte *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4d(GLuint, GLdouble, GLdouble, GLdouble, GLdouble) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4dv(GLuint, const GLdouble *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4f(GLuint, GLfloat, GLfloat, GLfloat, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4fv(GLuint, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4iv(GLuint, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4s(GLuint, GLshort, GLshort, GLshort, GLshort) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4sv(GLuint, const GLshort *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4ubv(GLuint, const GLubyte *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4uiv(GLuint, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttrib4usv(GLuint, const GLushort *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribPointer(GLuint, GLint, GLenum, GLboolean, GLsizei, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glUniformMatrix2x3fv(GLint, GLsizei, GLboolean, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniformMatrix2x4fv(GLint, GLsizei, GLboolean, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniformMatrix3x2fv(GLint, GLsizei, GLboolean, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniformMatrix3x4fv(GLint, GLsizei, GLboolean, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniformMatrix4x2fv(GLint, GLsizei, GLboolean, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glUniformMatrix4x3fv(GLint, GLsizei, GLboolean, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glBeginConditionalRender(GLuint, GLenum) {  }
static void CODEGEN_FUNCPTR null_glBeginTransformFeedback(GLenum) {  }
static void CODEGEN_FUNCPTR null_glBindBufferBase(GLenum, GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glBindBufferRange(GLenum, GLuint, GLuint, GLintptr, GLsizeiptr) {  }
static void CODEGEN_FUNCPTR null_glBindFragDataLocation(GLuint, GLuint, const GLchar *) {  }
static void CODEGEN_FUNCPTR null_glBindFramebuffer(GLenum, GLuint) {  }
static void CODEGEN_FUNCPTR null_glBindRenderbuffer(GLenum, GLuint) {  }
static void CODEGEN_FUNCPTR null_glBindVertexArray(GLuint) {  }
static void CODEGEN_FUNCPTR null_glBlitFramebuffer(GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLbitfield, GLenum) {  }
static GLenum CODEGEN_FUNCPTR null_glCheckFramebufferStatus(GLenum) { return 0x8CD5; /* GL_FRAMEBUFFER_COMPLETE */ }
static void CODEGEN_FUNCPTR null_glClampColor(GLenum, GLenum) {  }
static void CODEGEN_FUNCPTR null_glClearBufferfi(GLenum, GLint, GLfloat, GLint) {  }
static void CODEGEN_FUNCPTR null_glClearBufferfv(GLenum, GLint, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glClearBufferiv(GLenum, GLint, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glClearBufferuiv(GLenum, GLint, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glColorMaski(GLuint, GLboolean, GLboolean, GLboolean, GLboolean) {  }
static void CODEGEN_FUNCPTR null_glDeleteFramebuffers(GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glDeleteRenderbuffers(GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glDeleteVertexArrays(GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glDisablei(GLenum, GLuint) {  }
static void CODEGEN_FUNCPTR null_glEnablei(GLenum, GLuint) {  }
static void CODEGEN_FUNCPTR null_glEndConditionalRender(void) {  }
static void CODEGEN_FUNCPTR null_glEndTransformFeedback(void) {  }
static void CODEGEN_FUNCPTR null_glFlushMappedBufferRange(GLenum, GLintptr, GLsizeiptr) {  }
static void CODEGEN_FUNCPTR null_glFramebufferRenderbuffer(GLenum, GLenum, GLenum, GLuint) {  }
static void CODEGEN_FUNCPTR null_glFramebufferTexture1D(GLenum, GLenum, GLenum, GLuint, GLint) {  }
static void CODEGEN_FUNCPTR null_glFramebufferTexture2D(GLenum, GLenum, GLenum, GLuint, GLint) {  }
static void CODEGEN_FUNCPTR null_glFramebufferTexture3D(GLenum, GLenum, GLenum, GLuint, GLint, GLint) {  }
static void CODEGEN_FUNCPTR null_glFramebufferTextureLayer(GLenum, GLenum, GLuint, GLint, GLint) {  }
static void CODEGEN_FUNCPTR null_glGenFramebuffers(GLsizei, GLuint *) {  }
static void CODEGEN_FUNCPTR null_glGenRenderbuffers(GLsizei, GLuint *) {  }
static void CODEGEN_FUNCPTR null_glGenVertexArrays(GLsizei, GLuint *) {  }
static void CODEGEN_FUNCPTR null_glGenerateMipmap(GLenum) {  }
static void CODEGEN_FUNCPTR null_glGetBooleani_v(GLenum, GLuint, GLboolean *) {  }
static GLint CODEGEN_FUNCPTR null_glGetFragDataLocation(GLuint, const GLchar *) { return -1; }
static void CODEGEN_FUNCPTR null_glGetFramebufferAttachmentParameteriv(GLenum, GLenum, GLenum, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetIntegeri_v(GLenum, GLuint, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetRenderbufferParameteriv(GLenum, GLenum, GLint *) {  }
static const GLubyte * CODEGEN_FUNCPTR null_glGetStringi(GLenum, GLuint) { static const GLubyte s[] = ""; return s; }
static void CODEGEN_FUNCPTR null_glGetTexParameterIiv(GLenum, GLenum, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetTexParameterIuiv(GLenum, GLenum, GLuint *) {  }
static void CODEGEN_FUNCPTR null_glGetTransformFeedbackVarying(GLuint, GLuint, GLsizei, GLsizei *, GLsizei *, GLenum *, GLchar *) {  }
static void CODEGEN_FUNCPTR null_glGetUniformuiv(GLuint, GLint, GLuint *) {  }
static void CODEGEN_FUNCPTR null_glGetVertexAttribIiv(GLuint, GLenum, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetVertexAttribIuiv(GLuint, GLenum, GLuint *) {  }
static GLboolean CODEGEN_FUNCPTR null_glIsEnabledi(GLenum, GLuint) { return 0; }
static GLboolean CODEGEN_FUNCPTR null_glIsFramebuffer(GLuint) { return 0; }
static GLboolean CODEGEN_FUNCPTR null_glIsRenderbuffer(GLuint) { return 0; }
static GLboolean CODEGEN_FUNCPTR null_glIsVertexArray(GLuint) { return 0; }
static void * CODEGEN_FUNCPTR null_glMapBufferRange(GLenum, GLintptr, GLsizeiptr, GLbitfield) { return 0; }
static void CODEGEN_FUNCPTR null_glRenderbufferStorage(GLenum, GLenum, GLsizei, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glRenderbufferStorageMultisample(GLenum, GLsizei, GLenum, GLsizei, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glTexParameterIiv(GLenum, GLenum, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glTexParameterIuiv(GLenum, GLenum, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glTransformFeedbackVaryings(GLuint, GLsizei, const GLchar *const*, GLenum) {  }
static void CODEGEN_FUNCPTR null_glUniform1ui(GLint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glUniform1uiv(GLint, GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glUniform2ui(GLint, GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glUniform2uiv(GLint, GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glUniform3ui(GLint, GLuint, GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glUniform3uiv(GLint, GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glUniform4ui(GLint, GLuint, GLuint, GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glUniform4uiv(GLint, GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI1i(GLuint, GLint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI1iv(GLuint, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI1ui(GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI1uiv(GLuint, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI2i(GLuint, GLint, GLint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI2iv(GLuint, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI2ui(GLuint, GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI2uiv(GLuint, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI3i(GLuint, GLint, GLint, GLint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI3iv(GLuint, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI3ui(GLuint, GLuint, GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI3uiv(GLuint, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI4bv(GLuint, const GLbyte *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI4i(GLuint, GLint, GLint, GLint, GLint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI4iv(GLuint, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI4sv(GLuint, const GLshort *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI4ubv(GLuint, const GLubyte *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI4ui(GLuint, GLuint, GLuint, GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI4uiv(GLuint, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribI4usv(GLuint, const GLushort *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribIPointer(GLuint, GLint, GLenum, GLsizei, const GLvoid *) {  }
static void CODEGEN_FUNCPTR null_glCopyBufferSubData(GLenum, GLenum, GLintptr, GLintptr, GLsizeiptr) {  }
static void CODEGEN_FUNCPTR null_glDrawArraysInstanced(GLenum, GLint, GLsizei, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glDrawElementsInstanced(GLenum, GLsizei, GLenum, const GLvoid *, GLsizei) {  }
static void CODEGEN_FUNCPTR null_glGetActiveUniformBlockName(GLuint, GLuint, GLsizei, GLsizei *, GLchar *) {  }
static void CODEGEN_FUNCPTR null_glGetActiveUniformBlockiv(GLuint, GLuint, GLenum, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetActiveUniformName(GLuint, GLuint, GLsizei, GLsizei *, GLchar *) {  }
static void CODEGEN_FUNCPTR null_glGetActiveUniformsiv(GLuint, GLsizei, const GLuint *, GLenum, GLint *) {  }
static GLuint CODEGEN_FUNCPTR null_glGetUniformBlockIndex(GLuint, const GLchar *) { return 0; }
static void CODEGEN_FUNCPTR null_glGetUniformIndices(GLuint, GLsizei, const GLchar *const*, GLuint *) {  }
static void CODEGEN_FUNCPTR null_glPrimitiveRestartIndex(GLuint) {  }
static void CODEGEN_FUNCPTR null_glTexBuffer(GLenum, GLenum, GLuint) {  }
static void CODEGEN_FUNCPTR null_glUniformBlockBinding(GLuint, GLuint, GLuint) {  }
static GLenum CODEGEN_FUNCPTR null_glClientWaitSync(GLsync, GLbitfield, GLuint64) { return 0; }
static void CODEGEN_FUNCPTR null_glDeleteSync(GLsync) {  }
static void CODEGEN_FUNCPTR null_glDrawElementsBaseVertex(GLenum, GLsizei, GLenum, const GLvoid *, GLint) {  }
static void CODEGEN_FUNCPTR null_glDrawElementsInstancedBaseVertex(GLenum, GLsizei, GLenum, const GLvoid *, GLsizei, GLint) {  }
static void CODEGEN_FUNCPTR null_glDrawRangeElementsBaseVertex(GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *, GLint) {  }
static GLsync CODEGEN_FUNCPTR null_glFenceSync(GLenum, GLbitfield) { return 0; }
static void CODEGEN_FUNCPTR null_glFramebufferTexture(GLenum, GLenum, GLuint, GLint) {  }
static void CODEGEN_FUNCPTR null_glGetBufferParameteri64v(GLenum, GLenum, GLint64 *) {  }
static void CODEGEN_FUNCPTR null_glGetInteger64i_v(GLenum, GLuint, GLint64 *) {  }
static void CODEGEN_FUNCPTR null_glGetInteger64v(GLenum, GLint64 *) {  }
static void CODEGEN_FUNCPTR null_glGetMultisamplefv(GLenum, GLuint, GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glGetSynciv(GLsync, GLenum, GLsizei, GLsizei *, GLint *) {  }
static GLboolean CODEGEN_FUNCPTR null_glIsSync(GLsync) { return 0; }
static void CODEGEN_FUNCPTR null_glMultiDrawElementsBaseVertex(GLenum, const GLsizei *, GLenum, const GLvoid *const*, GLsizei, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glProvokingVertex(GLenum) {  }
static void CODEGEN_FUNCPTR null_glSampleMaski(GLuint, GLbitfield) {  }
static void CODEGEN_FUNCPTR null_glTexImage2DMultisample(GLenum, GLsizei, GLint, GLsizei, GLsizei, GLboolean) {  }
static void CODEGEN_FUNCPTR null_glTexImage3DMultisample(GLenum, GLsizei, GLint, GLsizei, GLsizei, GLsizei, GLboolean) {  }
static void CODEGEN_FUNCPTR null_glWaitSync(GLsync, GLbitfield, GLuint64) {  }
static void CODEGEN_FUNCPTR null_glBindFragDataLocationIndexed(GLuint, GLuint, GLuint, const GLchar *) {  }
static void CODEGEN_FUNCPTR null_glBindSampler(GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glDeleteSamplers(GLsizei, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glGenSamplers(GLsizei, GLuint *) {  }
static GLint CODEGEN_FUNCPTR null_glGetFragDataIndex(GLuint, const GLchar *) { return 0; }
static void CODEGEN_FUNCPTR null_glGetQueryObjecti64v(GLuint, GLenum, GLint64 *) {  }
static void CODEGEN_FUNCPTR null_glGetQueryObjectui64v(GLuint, GLenum, GLuint64 *) {  }
static void CODEGEN_FUNCPTR null_glGetSamplerParameterIiv(GLuint, GLenum, GLint *) {  }
static void CODEGEN_FUNCPTR null_glGetSamplerParameterIuiv(GLuint, GLenum, GLuint *) {  }
static void CODEGEN_FUNCPTR null_glGetSamplerParameterfv(GLuint, GLenum, GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glGetSamplerParameteriv(GLuint, GLenum, GLint *) {  }
static GLboolean CODEGEN_FUNCPTR null_glIsSampler(GLuint) { return 0; }
static void CODEGEN_FUNCPTR null_glQueryCounter(GLuint, GLenum) {  }
static void CODEGEN_FUNCPTR null_glSamplerParameterIiv(GLuint, GLenum, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glSamplerParameterIuiv(GLuint, GLenum, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glSamplerParameterf(GLuint, GLenum, GLfloat) {  }
static void CODEGEN_FUNCPTR null_glSamplerParameterfv(GLuint, GLenum, const GLfloat *) {  }
static void CODEGEN_FUNCPTR null_glSamplerParameteri(GLuint, GLenum, GLint) {  }
static void CODEGEN_FUNCPTR null_glSamplerParameteriv(GLuint, GLenum, const GLint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribDivisor(GLuint, GLuint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribP1ui(GLuint, GLenum, GLboolean, GLuint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribP1uiv(GLuint, GLenum, GLboolean, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribP2ui(GLuint, GLenum, GLboolean, GLuint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribP2uiv(GLuint, GLenum, GLboolean, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribP3ui(GLuint, GLenum, GLboolean, GLuint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribP3uiv(GLuint, GLenum, GLboolean, const GLuint *) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribP4ui(GLuint, GLenum, GLboolean, GLuint) {  }
static void CODEGEN_FUNCPTR null_glVertexAttribP4uiv(GLuint, GLenum, GLboolean, const GLuint *) {  }

void (CODEGEN_FUNCPTR *_ptrc_glBlendFunc)(GLenum, GLenum) = null_glBlendFunc;
void (CODEGEN_FUNCPTR *_ptrc_glClear)(GLbitfield) = null_glClear;
void (CODEGEN_FUNCPTR *_ptrc_glClearColor)(GLfloat, GLfloat, GLfloat, GLfloat) = null_glClearColor;
void (CODEGEN_FUNCPTR *_ptrc_glClearDepth)(GLdouble) = null_glClearDepth;
void (CODEGEN_FUNCPTR *_ptrc_glClearStencil)(GLint) = null_glClearStencil;
void (CODEGEN_FUNCPTR *_ptrc_glColorMask)(GLboolean, GLboolean, GLboolean, GLboolean) = null_glColorMask;
void (CODEGEN_FUNCPTR *_ptrc_glCullFace)(GLenum) = null_glCullFace;
void (CODEGEN_FUNCPTR *_ptrc_glDepthFunc)(GLenum) = null_glDepthFunc;
void (CODEGEN_FUNCPTR *_ptrc_glDepthMask)(GLboolean) = null_glDepthMask;
void (CODEGEN_FUNCPTR *_ptrc_glDepthRange)(GLdouble, GLdouble) = null_glDepthRange;
void (CODEGEN_FUNCPTR *_ptrc_glDisable)(GLenum) = null_glDisable;
void (CODEGEN_FUNCPTR *_ptrc_glDrawBuffer)(GLenum) = null_glDrawBuffer;
void (CODEGEN_FUNCPTR *_ptrc_glEnable)(GLenum) = null_glEnable;
void (CODEGEN_FUNCPTR *_ptrc_glFinish)(void) = null_glFinish;
void (CODEGEN_FUNCPTR *_ptrc_glFlush)(void) = null_glFlush;
void (CODEGEN_FUNCPTR *_ptrc_glFrontFace)(GLenum) = null_glFrontFace;
void (CODEGEN_FUNCPTR *_ptrc_glGetBooleanv)(GLenum, GLboolean *) = null_glGetBooleanv;
void (CODEGEN_FUNCPTR *_ptrc_glGetDoublev)(GLenum, GLdouble *) = null_glGetDoublev;
GLenum (CODEGEN_FUNCPTR *_ptrc_glGetError)(void) = null_glGetError;
void (CODEGEN_FUNCPTR *_ptrc_glGetFloatv)(GLenum, GLfloat *) = null_glGetFloatv;
void (CODEGEN_FUNCPTR *_ptrc_glGetIntegerv)(GLenum, GLint *) = null_glGetIntegerv;
const GLubyte * (CODEGEN_FUNCPTR *_ptrc_glGetString)(GLenum) = null_glGetString;
void (CODEGEN_FUNCPTR *_ptrc_glGetTexImage)(GLenum, GLint, GLenum, GLenum, GLvoid *) = null_glGetTexImage;
void (CODEGEN_FUNCPTR *_ptrc_glGetTexLevelParameterfv)(GLenum, GLint, GLenum, GLfloat *) = null_glGetTexLevelParameterfv;
void (CODEGEN_FUNCPTR *_ptrc_glGetTexLevelParameteriv)(GLenum, GLint, GLenum, GLint *) = null_glGetTexLevelParameteriv;
void (CODEGEN_FUNCPTR *_ptrc_glGetTexParameterfv)(GLenum, GLenum, GLfloat *) = null_glGetTexParameterfv;
void (CODEGEN_FUNCPTR *_ptrc_glGetTexParameteriv)(GLenum, GLenum, GLint *) = null_glGetTexParameteriv;
void (CODEGEN_FUNCPTR *_ptrc_glHint)(GLenum, GLenum) = null_glHint;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsEnabled)(GLenum) = null_glIsEnabled;
void (CODEGEN_FUNCPTR *_ptrc_glLineWidth)(GLfloat) = null_glLineWidth;
void (CODEGEN_FUNCPTR *_ptrc_glLogicOp)(GLenum) = null_glLogicOp;
void (CODEGEN_FUNCPTR *_ptrc_glPixelStoref)(GLenum, GLfloat) = null_glPixelStoref;
void (CODEGEN_FUNCPTR *_ptrc_glPixelStorei)(GLenum, GLint) = null_glPixelStorei;
void (CODEGEN_FUNCPTR *_ptrc_glPointSize)(GLfloat) = null_glPointSize;
void (CODEGEN_FUNCPTR *_ptrc_glPolygonMode)(GLenum, GLenum) = null_glPolygonMode;
void (CODEGEN_FUNCPTR *_ptrc_glReadBuffer)(GLenum) = null_glReadBuffer;
void (CODEGEN_FUNCPTR *_ptrc_glReadPixels)(GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *) = null_glReadPixels;
void (CODEGEN_FUNCPTR *_ptrc_glScissor)(GLint, GLint, GLsizei, GLsizei) = null_glScissor;
void (CODEGEN_FUNCPTR *_ptrc_glStencilFunc)(GLenum, GLint, GLuint) = null_glStencilFunc;
void (CODEGEN_FUNCPTR *_ptrc_glStencilMask)(GLuint) = null_glStencilMask;
void (CODEGEN_FUNCPTR *_ptrc_glStencilOp)(GLenum, GLenum, GLenum) = null_glStencilOp;
void (CODEGEN_FUNCPTR *_ptrc_glTexImage1D)(GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, const GLvoid *) = null_glTexImage1D;
void (CODEGEN_FUNCPTR *_ptrc_glTexImage2D)(GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *) = null_glTexImage2D;
void (CODEGEN_FUNCPTR *_ptrc_glTexParameterf)(GLenum, GLenum, GLfloat) = null_glTexParameterf;
void (CODEGEN_FUNCPTR *_ptrc_glTexParameterfv)(GLenum, GLenum, const GLfloat *) = null_glTexParameterfv;
void (CODEGEN_FUNCPTR *_ptrc_glTexParameteri)(GLenum, GLenum, GLint) = null_glTexParameteri;
void (CODEGEN_FUNCPTR *_ptrc_glTexParameteriv)(GLenum, GLenum, const GLint *) = null_glTexParameteriv;
void (CODEGEN_FUNCPTR *_ptrc_glViewport)(GLint, GLint, GLsizei, GLsizei) = null_glViewport;
void (CODEGEN_FUNCPTR *_ptrc_glBindTexture)(GLenum, GLuint) = null_glBindTexture;
void (CODEGEN_FUNCPTR *_ptrc_glCopyTexImage1D)(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint) = null_glCopyTexImage1D;
void (CODEGEN_FUNCPTR *_ptrc_glCopyTexImage2D)(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint) = null_glCopyTexImage2D;
void (CODEGEN_FUNCPTR *_ptrc_glCopyTexSubImage1D)(GLenum, GLint, GLint, GLint, GLint, GLsizei) = null_glCopyTexSubImage1D;
void (CODEGEN_FUNCPTR *_ptrc_glCopyTexSubImage2D)(GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei) = null_glCopyTexSubImage2D;
void (CODEGEN_FUNCPTR *_ptrc_glDeleteTextures)(GLsizei, const GLuint *) = null_glDeleteTextures;
void (CODEGEN_FUNCPTR *_ptrc_glDrawArrays)(GLenum, GLint, GLsizei) = null_glDrawArrays;
void (CODEGEN_FUNCPTR *_ptrc_glDrawElements)(GLenum, GLsizei, GLenum, const GLvoid *) = null_glDrawElements;
void (CODEGEN_FUNCPTR *_ptrc_glGenTextures)(GLsizei, GLuint *) = null_glGenTextures;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsTexture)(GLuint) = null_glIsTexture;
void (CODEGEN_FUNCPTR *_ptrc_glPolygonOffset)(GLfloat, GLfloat) = null_glPolygonOffset;
void (CODEGEN_FUNCPTR *_ptrc_glTexSubImage1D)(GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const GLvoid *) = null_glTexSubImage1D;
void (CODEGEN_FUNCPTR *_ptrc_glTexSubImage2D)(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *) = null_glTexSubImage2D;
void (CODEGEN_FUNCPTR *_ptrc_glBlendColor)(GLfloat, GLfloat, GLfloat, GLfloat) = null_glBlendColor;
void (CODEGEN_FUNCPTR *_ptrc_glBlendEquation)(GLenum) = null_glBlendEquation;
void (CODEGEN_FUNCPTR *_ptrc_glCopyTexSubImage3D)(GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei) = null_glCopyTexSubImage3D;
void (CODEGEN_FUNCPTR *_ptrc_glDrawRangeElements)(GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *) = null_glDrawRangeElements;
void (CODEGEN_FUNCPTR *_ptrc_glTexImage3D)(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *) = null_glTexImage3D;
void (CODEGEN_FUNCPTR *_ptrc_glTexSubImage3D)(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *) = null_glTexSubImage3D;
void (CODEGEN_FUNCPTR *_ptrc_glActiveTexture)(GLenum) = null_glActiveTexture;
void (CODEGEN_FUNCPTR *_ptrc_glCompressedTexImage1D)(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *) = null_glCompressedTexImage1D;
void (CODEGEN_FUNCPTR *_ptrc_glCompressedTexImage2D)(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *) = null_glCompressedTexImage2D;
void (CODEGEN_FUNCPTR *_ptrc_glCompressedTexImage3D)(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *) = null_glCompressedTexImage3D;
void (CODEGEN_FUNCPTR *_ptrc_glCompressedTexSubImage1D)(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *) = null_glCompressedTexSubImage1D;
void (CODEGEN_FUNCPTR *_ptrc_glCompressedTexSubImage2D)(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *) = null_glCompressedTexSubImage2D;
void (CODEGEN_FUNCPTR *_ptrc_glCompressedTexSubImage3D)(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *) = null_glCompressedTexSubImage3D;
void (CODEGEN_FUNCPTR *_ptrc_glGetCompressedTexImage)(GLenum, GLint, GLvoid *) = null_glGetCompressedTexImage;
void (CODEGEN_FUNCPTR *_ptrc_glSampleCoverage)(GLfloat, GLboolean) = null_glSampleCoverage;
void (CODEGEN_FUNCPTR *_ptrc_glBlendFuncSeparate)(GLenum, GLenum, GLenum, GLenum) = null_glBlendFuncSeparate;
void (CODEGEN_FUNCPTR *_ptrc_glMultiDrawArrays)(GLenum, const GLint *, const GLsizei *, GLsizei) = null_glMultiDrawArrays;
void (CODEGEN_FUNCPTR *_ptrc_glMultiDrawElements)(GLenum, const GLsizei *, GLenum, const GLvoid *const*, GLsizei) = null_glMultiDrawElements;
void (CODEGEN_FUNCPTR *_ptrc_glPointParameterf)(GLenum, GLfloat) = null_glPointParameterf;
void (CODEGEN_FUNCPTR *_ptrc_glPointParameterfv)(GLenum, const GLfloat *) = null_glPointParameterfv;
void (CODEGEN_FUNCPTR *_ptrc_glPointParameteri)(GLenum, GLint) = null_glPointParameteri;
void (CODEGEN_FUNCPTR *_ptrc_glPointParameteriv)(GLenum, const GLint *) = null_glPointParameteriv;
void (CODEGEN_FUNCPTR *_ptrc_glBeginQuery)(GLenum, GLuint) = null_glBeginQuery;
void (CODEGEN_FUNCPTR *_ptrc_glBindBuffer)(GLenum, GLuint) = null_glBindBuffer;
void (CODEGEN_FUNCPTR *_ptrc_glBufferData)(GLenum, GLsizeiptr, const GLvoid *, GLenum) = null_glBufferData;
void (CODEGEN_FUNCPTR *_ptrc_glBufferSubData)(GLenum, GLintptr, GLsizeiptr, const GLvoid *) = null_glBufferSubData;
void (CODEGEN_FUNCPTR *_ptrc_glDeleteBuffers)(GLsizei, const GLuint *) = null_glDeleteBuffers;
void (CODEGEN_FUNCPTR *_ptrc_glDeleteQueries)(GLsizei, const GLuint *) = null_glDeleteQueries;
void (CODEGEN_FUNCPTR *_ptrc_glEndQuery)(GLenum) = null_glEndQuery;
void (CODEGEN_FUNCPTR *_ptrc_glGenBuffers)(GLsizei, GLuint *) = null_glGenBuffers;
void (CODEGEN_FUNCPTR *_ptrc_glGenQueries)(GLsizei, GLuint *) = null_glGenQueries;
void (CODEGEN_FUNCPTR *_ptrc_glGetBufferParameteriv)(GLenum, GLenum, GLint *) = null_glGetBufferParameteriv;
void (CODEGEN_FUNCPTR *_ptrc_glGetBufferPointerv)(GLenum, GLenum, GLvoid **) = null_glGetBufferPointerv;
void (CODEGEN_FUNCPTR *_ptrc_glGetBufferSubData)(GLenum, GLintptr, GLsizeiptr, GLvoid *) = null_glGetBufferSubData;
void (CODEGEN_FUNCPTR *_ptrc_glGetQueryObjectiv)(GLuint, GLenum, GLint *) = null_glGetQueryObjectiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetQueryObjectuiv)(GLuint, GLenum, GLuint *) = null_glGetQueryObjectuiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetQueryiv)(GLenum, GLenum, GLint *) = null_glGetQueryiv;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsBuffer)(GLuint) = null_glIsBuffer;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsQuery)(GLuint) = null_glIsQuery;
void * (CODEGEN_FUNCPTR *_ptrc_glMapBuffer)(GLenum, GLenum) = null_glMapBuffer;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glUnmapBuffer)(GLenum) = null_glUnmapBuffer;
void (CODEGEN_FUNCPTR *_ptrc_glAttachShader)(GLuint, GLuint) = null_glAttachShader;
void (CODEGEN_FUNCPTR *_ptrc_glBindAttribLocation)(GLuint, GLuint, const GLchar *) = null_glBindAttribLocation;
void (CODEGEN_FUNCPTR *_ptrc_glBlendEquationSeparate)(GLenum, GLenum) = null_glBlendEquationSeparate;
void (CODEGEN_FUNCPTR *_ptrc_glCompileShader)(GLuint) = null_glCompileShader;
GLuint (CODEGEN_FUNCPTR *_ptrc_glCreateProgram)(void) = null_glCreateProgram;
GLuint (CODEGEN_FUNCPTR *_ptrc_glCreateShader)(GLenum) = null_glCreateShader;
void (CODEGEN_FUNCPTR *_ptrc_glDeleteProgram)(GLuint) = null_glDeleteProgram;
void (CODEGEN_FUNCPTR *_ptrc_glDeleteShader)(GLuint) = null_glDeleteShader;
void (CODEGEN_FUNCPTR *_ptrc_glDetachShader)(GLuint, GLuint) = null_glDetachShader;
void (CODEGEN_FUNCPTR *_ptrc_glDisableVertexAttribArray)(GLuint) = null_glDisableVertexAttribArray;
void (CODEGEN_FUNCPTR *_ptrc_glDrawBuffers)(GLsizei, const GLenum *) = null_glDrawBuffers;
void (CODEGEN_FUNCPTR *_ptrc_glEnableVertexAttribArray)(GLuint) = null_glEnableVertexAttribArray;
void (CODEGEN_FUNCPTR *_ptrc_glGetActiveAttrib)(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *) = null_glGetActiveAttrib;
void (CODEGEN_FUNCPTR *_ptrc_glGetActiveUniform)(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *) = null_glGetActiveUniform;
void (CODEGEN_FUNCPTR *_ptrc_glGetAttachedShaders)(GLuint, GLsizei, GLsizei *, GLuint *) = null_glGetAttachedShaders;
GLint (CODEGEN_FUNCPTR *_ptrc_glGetAttribLocation)(GLuint, const GLchar *) = null_glGetAttribLocation;
void (CODEGEN_FUNCPTR *_ptrc_glGetProgramInfoLog)(GLuint, GLsizei, GLsizei *, GLchar *) = null_glGetProgramInfoLog;
void (CODEGEN_FUNCPTR *_ptrc_glGetProgramiv)(GLuint, GLenum, GLint *) = null_glGetProgramiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetShaderInfoLog)(GLuint, GLsizei, GLsizei *, GLchar *) = null_glGetShaderInfoLog;
void (CODEGEN_FUNCPTR *_ptrc_glGetShaderSource)(GLuint, GLsizei, GLsizei *, GLchar *) = null_glGetShaderSource;
void (CODEGEN_FUNCPTR *_ptrc_glGetShaderiv)(GLuint, GLenum, GLint *) = null_glGetShaderiv;
GLint (CODEGEN_FUNCPTR *_ptrc_glGetUniformLocation)(GLuint, const GLchar *) = null_glGetUniformLocation;
void (CODEGEN_FUNCPTR *_ptrc_glGetUniformfv)(GLuint, GLint, GLfloat *) = null_glGetUniformfv;
void (CODEGEN_FUNCPTR *_ptrc_glGetUniformiv)(GLuint, GLint, GLint *) = null_glGetUniformiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetVertexAttribPointerv)(GLuint, GLenum, GLvoid **) = null_glGetVertexAttribPointerv;
void (CODEGEN_FUNCPTR *_ptrc_glGetVertexAttribdv)(GLuint, GLenum, GLdouble *) = null_glGetVertexAttribdv;
void (CODEGEN_FUNCPTR *_ptrc_glGetVertexAttribfv)(GLuint, GLenum, GLfloat *) = null_glGetVertexAttribfv;
void (CODEGEN_FUNCPTR *_ptrc_glGetVertexAttribiv)(GLuint, GLenum, GLint *) = null_glGetVertexAttribiv;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsProgram)(GLuint) = null_glIsProgram;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsShader)(GLuint) = null_glIsShader;
void (CODEGEN_FUNCPTR *_ptrc_glLinkProgram)(GLuint) = null_glLinkProgram;
void (CODEGEN_FUNCPTR *_ptrc_glShaderSource)(GLuint, GLsizei, const GLchar *const*, const GLint *) = null_glShaderSource;
void (CODEGEN_FUNCPTR *_ptrc_glStencilFuncSeparate)(GLenum, GLenum, GLint, GLuint) = null_glStencilFuncSeparate;
void (CODEGEN_FUNCPTR *_ptrc_glStencilMaskSeparate)(GLenum, GLuint) = null_glStencilMaskSeparate;
void (CODEGEN_FUNCPTR *_ptrc_glStencilOpSeparate)(GLenum, GLenum, GLenum, GLenum) = null_glStencilOpSeparate;
void (CODEGEN_FUNCPTR *_ptrc_glUniform1f)(GLint, GLfloat) = null_glUniform1f;
void (CODEGEN_FUNCPTR *_ptrc_glUniform1fv)(GLint, GLsizei, const GLfloat *) = null_glUniform1fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniform1i)(GLint, GLint) = null_glUniform1i;
void (CODEGEN_FUNCPTR *_ptrc_glUniform1iv)(GLint, GLsizei, const GLint *) = null_glUniform1iv;
void (CODEGEN_FUNCPTR *_ptrc_glUniform2f)(GLint, GLfloat, GLfloat) = null_glUniform2f;
void (CODEGEN_FUNCPTR *_ptrc_glUniform2fv)(GLint, GLsizei, const GLfloat *) = null_glUniform2fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniform2i)(GLint, GLint, GLint) = null_glUniform2i;
void (CODEGEN_FUNCPTR *_ptrc_glUniform2iv)(GLint, GLsizei, const GLint *) = null_glUniform2iv;
void (CODEGEN_FUNCPTR *_ptrc_glUniform3f)(GLint, GLfloat, GLfloat, GLfloat) = null_glUniform3f;
void (CODEGEN_FUNCPTR *_ptrc_glUniform3fv)(GLint, GLsizei, const GLfloat *) = null_glUniform3fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniform3i)(GLint, GLint, GLint, GLint) = null_glUniform3i;
void (CODEGEN_FUNCPTR *_ptrc_glUniform3iv)(GLint, GLsizei, const GLint *) = null_glUniform3iv;
void (CODEGEN_FUNCPTR *_ptrc_glUniform4f)(GLint, GLfloat, GLfloat, GLfloat, GLfloat) = null_glUniform4f;
void (CODEGEN_FUNCPTR *_ptrc_glUniform4fv)(GLint, GLsizei, const GLfloat *) = null_glUniform4fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniform4i)(GLint, GLint, GLint, GLint, GLint) = null_glUniform4i;
void (CODEGEN_FUNCPTR *_ptrc_glUniform4iv)(GLint, GLsizei, const GLint *) = null_glUniform4iv;
void (CODEGEN_FUNCPTR *_ptrc_glUniformMatrix2fv)(GLint, GLsizei, GLboolean, const GLfloat *) = null_glUniformMatrix2fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniformMatrix3fv)(GLint, GLsizei, GLboolean, const GLfloat *) = null_glUniformMatrix3fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniformMatrix4fv)(GLint, GLsizei, GLboolean, const GLfloat *) = null_glUniformMatrix4fv;
void (CODEGEN_FUNCPTR *_ptrc_glUseProgram)(GLuint) = null_glUseProgram;
void (CODEGEN_FUNCPTR *_ptrc_glValidateProgram)(GLuint) = null_glValidateProgram;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib1d)(GLuint, GLdouble) = null_glVertexAttrib1d;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib1dv)(GLuint, const GLdouble *) = null_glVertexAttrib1dv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib1f)(GLuint, GLfloat) = null_glVertexAttrib1f;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib1fv)(GLuint, const GLfloat *) = null_glVertexAttrib1fv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib1s)(GLuint, GLshort) = null_glVertexAttrib1s;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib1sv)(GLuint, const GLshort *) = null_glVertexAttrib1sv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib2d)(GLuint, GLdouble, GLdouble) = null_glVertexAttrib2d;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib2dv)(GLuint, const GLdouble *) = null_glVertexAttrib2dv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib2f)(GLuint, GLfloat, GLfloat) = null_glVertexAttrib2f;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib2fv)(GLuint, const GLfloat *) = null_glVertexAttrib2fv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib2s)(GLuint, GLshort, GLshort) = null_glVertexAttrib2s;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib2sv)(GLuint, const GLshort *) = null_glVertexAttrib2sv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib3d)(GLuint, GLdouble, GLdouble, GLdouble) = null_glVertexAttrib3d;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib3dv)(GLuint, const GLdouble *) = null_glVertexAttrib3dv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib3f)(GLuint, GLfloat, GLfloat, GLfloat) = null_glVertexAttrib3f;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib3fv)(GLuint, const GLfloat *) = null_glVertexAttrib3fv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib3s)(GLuint, GLshort, GLshort, GLshort) = null_glVertexAttrib3s;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib3sv)(GLuint, const GLshort *) = null_glVertexAttrib3sv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4Nbv)(GLuint, const GLbyte *) = null_glVertexAttrib4Nbv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4Niv)(GLuint, const GLint *) = null_glVertexAttrib4Niv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4Nsv)(GLuint, const GLshort *) = null_glVertexAttrib4Nsv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4Nub)(GLuint, GLubyte, GLubyte, GLubyte, GLubyte) = null_glVertexAttrib4Nub;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4Nubv)(GLuint, const GLubyte *) = null_glVertexAttrib4Nubv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4Nuiv)(GLuint, const GLuint *) = null_glVertexAttrib4Nuiv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4Nusv)(GLuint, const GLushort *) = null_glVertexAttrib4Nusv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4bv)(GLuint, const GLbyte *) = null_glVertexAttrib4bv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4d)(GLuint, GLdouble, GLdouble, GLdouble, GLdouble) = null_glVertexAttrib4d;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4dv)(GLuint, const GLdouble *) = null_glVertexAttrib4dv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4f)(GLuint, GLfloat, GLfloat, GLfloat, GLfloat) = null_glVertexAttrib4f;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4fv)(GLuint, const GLfloat *) = null_glVertexAttrib4fv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4iv)(GLuint, const GLint *) = null_glVertexAttrib4iv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4s)(GLuint, GLshort, GLshort, GLshort, GLshort) = null_glVertexAttrib4s;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4sv)(GLuint, const GLshort *) = null_glVertexAttrib4sv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4ubv)(GLuint, const GLubyte *) = null_glVertexAttrib4ubv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4uiv)(GLuint, const GLuint *) = null_glVertexAttrib4uiv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttrib4usv)(GLuint, const GLushort *) = null_glVertexAttrib4usv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribPointer)(GLuint, GLint, GLenum, GLboolean, GLsizei, const GLvoid *) = null_glVertexAttribPointer;
void (CODEGEN_FUNCPTR *_ptrc_glUniformMatrix2x3fv)(GLint, GLsizei, GLboolean, const GLfloat *) = null_glUniformMatrix2x3fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniformMatrix2x4fv)(GLint, GLsizei, GLboolean, const GLfloat *) = null_glUniformMatrix2x4fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniformMatrix3x2fv)(GLint, GLsizei, GLboolean, const GLfloat *) = null_glUniformMatrix3x2fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniformMatrix3x4fv)(GLint, GLsizei, GLboolean, const GLfloat *) = null_glUniformMatrix3x4fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniformMatrix4x2fv)(GLint, GLsizei, GLboolean, const GLfloat *) = null_glUniformMatrix4x2fv;
void (CODEGEN_FUNCPTR *_ptrc_glUniformMatrix4x3fv)(GLint, GLsizei, GLboolean, const GLfloat *) = null_glUniformMatrix4x3fv;
void (CODEGEN_FUNCPTR *_ptrc_glBeginConditionalRender)(GLuint, GLenum) = null_glBeginConditionalRender;
void (CODEGEN_FUNCPTR *_ptrc_glBeginTransformFeedback)(GLenum) = null_glBeginTransformFeedback;
void (CODEGEN_FUNCPTR *_ptrc_glBindBufferBase)(GLenum, GLuint, GLuint) = null_glBindBufferBase;
void (CODEGEN_FUNCPTR *_ptrc_glBindBufferRange)(GLenum, GLuint, GLuint, GLintptr, GLsizeiptr) = null_glBindBufferRange;
void (CODEGEN_FUNCPTR *_ptrc_glBindFragDataLocation)(GLuint, GLuint, const GLchar *) = null_glBindFragDataLocation;
void (CODEGEN_FUNCPTR *_ptrc_glBindFramebuffer)(GLenum, GLuint) = null_glBindFramebuffer;
void (CODEGEN_FUNCPTR *_ptrc_glBindRenderbuffer)(GLenum, GLuint) = null_glBindRenderbuffer;
void (CODEGEN_FUNCPTR *_ptrc_glBindVertexArray)(GLuint) = null_glBindVertexArray;
void (CODEGEN_FUNCPTR *_ptrc_glBlitFramebuffer)(GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLbitfield, GLenum) = null_glBlitFramebuffer;
GLenum (CODEGEN_FUNCPTR *_ptrc_glCheckFramebufferStatus)(GLenum) = null_glCheckFramebufferStatus;
void (CODEGEN_FUNCPTR *_ptrc_glClampColor)(GLenum, GLenum) = null_glClampColor;
void (CODEGEN_FUNCPTR *_ptrc_glClearBufferfi)(GLenum, GLint, GLfloat, GLint) = null_glClearBufferfi;
void (CODEGEN_FUNCPTR *_ptrc_glClearBufferfv)(GLenum, GLint, const GLfloat *) = null_glClearBufferfv;
void (CODEGEN_FUNCPTR *_ptrc_glClearBufferiv)(GLenum, GLint, const GLint *) = null_glClearBufferiv;
void (CODEGEN_FUNCPTR *_ptrc_glClearBufferuiv)(GLenum, GLint, const GLuint *) = null_glClearBufferuiv;
void (CODEGEN_FUNCPTR *_ptrc_glColorMaski)(GLuint, GLboolean, GLboolean, GLboolean, GLboolean) = null_glColorMaski;
void (CODEGEN_FUNCPTR *_ptrc_glDeleteFramebuffers)(GLsizei, const GLuint *) = null_glDeleteFramebuffers;
void (CODEGEN_FUNCPTR *_ptrc_glDeleteRenderbuffers)(GLsizei, const GLuint *) = null_glDeleteRenderbuffers;
void (CODEGEN_FUNCPTR *_ptrc_glDeleteVertexArrays)(GLsizei, const GLuint *) = null_glDeleteVertexArrays;
void (CODEGEN_FUNCPTR *_ptrc_glDisablei)(GLenum, GLuint) = null_glDisablei;
void (CODEGEN_FUNCPTR *_ptrc_glEnablei)(GLenum, GLuint) = null_glEnablei;
void (CODEGEN_FUNCPTR *_ptrc_glEndConditionalRender)(void) = null_glEndConditionalRender;
void (CODEGEN_FUNCPTR *_ptrc_glEndTransformFeedback)(void) = null_glEndTransformFeedback;
void (CODEGEN_FUNCPTR *_ptrc_glFlushMappedBufferRange)(GLenum, GLintptr, GLsizeiptr) = null_glFlushMappedBufferRange;
void (CODEGEN_FUNCPTR *_ptrc_glFramebufferRenderbuffer)(GLenum, GLenum, GLenum, GLuint) = null_glFramebufferRenderbuffer;
void (CODEGEN_FUNCPTR *_ptrc_glFramebufferTexture1D)(GLenum, GLenum, GLenum, GLuint, GLint) = null_glFramebufferTexture1D;
void (CODEGEN_FUNCPTR *_ptrc_glFramebufferTexture2D)(GLenum, GLenum, GLenum, GLuint, GLint) = null_glFramebufferTexture2D;
void (CODEGEN_FUNCPTR *_ptrc_glFramebufferTexture3D)(GLenum, GLenum, GLenum, GLuint, GLint, GLint) = null_glFramebufferTexture3D;
void (CODEGEN_FUNCPTR *_ptrc_glFramebufferTextureLayer)(GLenum, GLenum, GLuint, GLint, GLint) = null_glFramebufferTextureLayer;
void (CODEGEN_FUNCPTR *_ptrc_glGenFramebuffers)(GLsizei, GLuint *) = null_glGenFramebuffers;
void (CODEGEN_FUNCPTR *_ptrc_glGenRenderbuffers)(GLsizei, GLuint *) = null_glGenRenderbuffers;
void (CODEGEN_FUNCPTR *_ptrc_glGenVertexArrays)(GLsizei, GLuint *) = null_glGenVertexArrays;
void (CODEGEN_FUNCPTR *_ptrc_glGenerateMipmap)(GLenum) = null_glGenerateMipmap;
void (CODEGEN_FUNCPTR *_ptrc_glGetBooleani_v)(GLenum, GLuint, GLboolean *) = null_glGetBooleani_v;
GLint (CODEGEN_FUNCPTR *_ptrc_glGetFragDataLocation)(GLuint, const GLchar *) = null_glGetFragDataLocation;
void (CODEGEN_FUNCPTR *_ptrc_glGetFramebufferAttachmentParameteriv)(GLenum, GLenum, GLenum, GLint *) = null_glGetFramebufferAttachmentParameteriv;
void (CODEGEN_FUNCPTR *_ptrc_glGetIntegeri_v)(GLenum, GLuint, GLint *) = null_glGetIntegeri_v;
void (CODEGEN_FUNCPTR *_ptrc_glGetRenderbufferParameteriv)(GLenum, GLenum, GLint *) = null_glGetRenderbufferParameteriv;
const GLubyte * (CODEGEN_FUNCPTR *_ptrc_glGetStringi)(GLenum, GLuint) = null_glGetStringi;
void (CODEGEN_FUNCPTR *_ptrc_glGetTexParameterIiv)(GLenum, GLenum, GLint *) = null_glGetTexParameterIiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetTexParameterIuiv)(GLenum, GLenum, GLuint *) = null_glGetTexParameterIuiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetTransformFeedbackVarying)(GLuint, GLuint, GLsizei, GLsizei *, GLsizei *, GLenum *, GLchar *) = null_glGetTransformFeedbackVarying;
void (CODEGEN_FUNCPTR *_ptrc_glGetUniformuiv)(GLuint, GLint, GLuint *) = null_glGetUniformuiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetVertexAttribIiv)(GLuint, GLenum, GLint *) = null_glGetVertexAttribIiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetVertexAttribIuiv)(GLuint, GLenum, GLuint *) = null_glGetVertexAttribIuiv;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsEnabledi)(GLenum, GLuint) = null_glIsEnabledi;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsFramebuffer)(GLuint) = null_glIsFramebuffer;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsRenderbuffer)(GLuint) = null_glIsRenderbuffer;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsVertexArray)(GLuint) = null_glIsVertexArray;
void * (CODEGEN_FUNCPTR *_ptrc_glMapBufferRange)(GLenum, GLintptr, GLsizeiptr, GLbitfield) = null_glMapBufferRange;
void (CODEGEN_FUNCPTR *_ptrc_glRenderbufferStorage)(GLenum, GLenum, GLsizei, GLsizei) = null_glRenderbufferStorage;
void (CODEGEN_FUNCPTR *_ptrc_glRenderbufferStorageMultisample)(GLenum, GLsizei, GLenum, GLsizei, GLsizei) = null_glRenderbufferStorageMultisample;
void (CODEGEN_FUNCPTR *_ptrc_glTexParameterIiv)(GLenum, GLenum, const GLint *) = null_glTexParameterIiv;
void (CODEGEN_FUNCPTR *_ptrc_glTexParameterIuiv)(GLenum, GLenum, const GLuint *) = null_glTexParameterIuiv;
void (CODEGEN_FUNCPTR *_ptrc_glTransformFeedbackVaryings)(GLuint, GLsizei, const GLchar *const*, GLenum) = null_glTransformFeedbackVaryings;
void (CODEGEN_FUNCPTR *_ptrc_glUniform1ui)(GLint, GLuint) = null_glUniform1ui;
void (CODEGEN_FUNCPTR *_ptrc_glUniform1uiv)(GLint, GLsizei, const GLuint *) = null_glUniform1uiv;
void (CODEGEN_FUNCPTR *_ptrc_glUniform2ui)(GLint, GLuint, GLuint) = null_glUniform2ui;
void (CODEGEN_FUNCPTR *_ptrc_glUniform2uiv)(GLint, GLsizei, const GLuint *) = null_glUniform2uiv;
void (CODEGEN_FUNCPTR *_ptrc_glUniform3ui)(GLint, GLuint, GLuint, GLuint) = null_glUniform3ui;
void (CODEGEN_FUNCPTR *_ptrc_glUniform3uiv)(GLint, GLsizei, const GLuint *) = null_glUniform3uiv;
void (CODEGEN_FUNCPTR *_ptrc_glUniform4ui)(GLint, GLuint, GLuint, GLuint, GLuint) = null_glUniform4ui;
void (CODEGEN_FUNCPTR *_ptrc_glUniform4uiv)(GLint, GLsizei, const GLuint *) = null_glUniform4uiv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI1i)(GLuint, GLint) = null_glVertexAttribI1i;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI1iv)(GLuint, const GLint *) = null_glVertexAttribI1iv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI1ui)(GLuint, GLuint) = null_glVertexAttribI1ui;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI1uiv)(GLuint, const GLuint *) = null_glVertexAttribI1uiv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI2i)(GLuint, GLint, GLint) = null_glVertexAttribI2i;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI2iv)(GLuint, const GLint *) = null_glVertexAttribI2iv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI2ui)(GLuint, GLuint, GLuint) = null_glVertexAttribI2ui;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI2uiv)(GLuint, const GLuint *) = null_glVertexAttribI2uiv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI3i)(GLuint, GLint, GLint, GLint) = null_glVertexAttribI3i;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI3iv)(GLuint, const GLint *) = null_glVertexAttribI3iv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI3ui)(GLuint, GLuint, GLuint, GLuint) = null_glVertexAttribI3ui;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI3uiv)(GLuint, const GLuint *) = null_glVertexAttribI3uiv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI4bv)(GLuint, const GLbyte *) = null_glVertexAttribI4bv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI4i)(GLuint, GLint, GLint, GLint, GLint) = null_glVertexAttribI4i;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI4iv)(GLuint, const GLint *) = null_glVertexAttribI4iv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI4sv)(GLuint, const GLshort *) = null_glVertexAttribI4sv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI4ubv)(GLuint, const GLubyte *) = null_glVertexAttribI4ubv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI4ui)(GLuint, GLuint, GLuint, GLuint, GLuint) = null_glVertexAttribI4ui;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI4uiv)(GLuint, const GLuint *) = null_glVertexAttribI4uiv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribI4usv)(GLuint, const GLushort *) = null_glVertexAttribI4usv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribIPointer)(GLuint, GLint, GLenum, GLsizei, const GLvoid *) = null_glVertexAttribIPointer;
void (CODEGEN_FUNCPTR *_ptrc_glCopyBufferSubData)(GLenum, GLenum, GLintptr, GLintptr, GLsizeiptr) = null_glCopyBufferSubData;
void (CODEGEN_FUNCPTR *_ptrc_glDrawArraysInstanced)(GLenum, GLint, GLsizei, GLsizei) = null_glDrawArraysInstanced;
void (CODEGEN_FUNCPTR *_ptrc_glDrawElementsInstanced)(GLenum, GLsizei, GLenum, const GLvoid *, GLsizei) = null_glDrawElementsInstanced;
void (CODEGEN_FUNCPTR *_ptrc_glGetActiveUniformBlockName)(GLuint, GLuint, GLsizei, GLsizei *, GLchar *) = null_glGetActiveUniformBlockName;
void (CODEGEN_FUNCPTR *_ptrc_glGetActiveUniformBlockiv)(GLuint, GLuint, GLenum, GLint *) = null_glGetActiveUniformBlockiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetActiveUniformName)(GLuint, GLuint, GLsizei, GLsizei *, GLchar *) = null_glGetActiveUniformName;
void (CODEGEN_FUNCPTR *_ptrc_glGetActiveUniformsiv)(GLuint, GLsizei, const GLuint *, GLenum, GLint *) = null_glGetActiveUniformsiv;
GLuint (CODEGEN_FUNCPTR *_ptrc_glGetUniformBlockIndex)(GLuint, const GLchar *) = null_glGetUniformBlockIndex;
void (CODEGEN_FUNCPTR *_ptrc_glGetUniformIndices)(GLuint, GLsizei, const GLchar *const*, GLuint *) = null_glGetUniformIndices;
void (CODEGEN_FUNCPTR *_ptrc_glPrimitiveRestartIndex)(GLuint) = null_glPrimitiveRestartIndex;
void (CODEGEN_FUNCPTR *_ptrc_glTexBuffer)(GLenum, GLenum, GLuint) = null_glTexBuffer;
void (CODEGEN_FUNCPTR *_ptrc_glUniformBlockBinding)(GLuint, GLuint, GLuint) = null_glUniformBlockBinding;
GLenum (CODEGEN_FUNCPTR *_ptrc_glClientWaitSync)(GLsync, GLbitfield, GLuint64) = null_glClientWaitSync;
void (CODEGEN_FUNCPTR *_ptrc_glDeleteSync)(GLsync) = null_glDeleteSync;
void (CODEGEN_FUNCPTR *_ptrc_glDrawElementsBaseVertex)(GLenum, GLsizei, GLenum, const GLvoid *, GLint) = null_glDrawElementsBaseVertex;
void (CODEGEN_FUNCPTR *_ptrc_glDrawElementsInstancedBaseVertex)(GLenum, GLsizei, GLenum, const GLvoid *, GLsizei, GLint) = null_glDrawElementsInstancedBaseVertex;
void (CODEGEN_FUNCPTR *_ptrc_glDrawRangeElementsBaseVertex)(GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *, GLint) = null_glDrawRangeElementsBaseVertex;
GLsync (CODEGEN_FUNCPTR *_ptrc_glFenceSync)(GLenum, GLbitfield) = null_glFenceSync;
void (CODEGEN_FUNCPTR *_ptrc_glFramebufferTexture)(GLenum, GLenum, GLuint, GLint) = null_glFramebufferTexture;
void (CODEGEN_FUNCPTR *_ptrc_glGetBufferParameteri64v)(GLenum, GLenum, GLint64 *) = null_glGetBufferParameteri64v;
void (CODEGEN_FUNCPTR *_ptrc_glGetInteger64i_v)(GLenum, GLuint, GLint64 *) = null_glGetInteger64i_v;
void (CODEGEN_FUNCPTR *_ptrc_glGetInteger64v)(GLenum, GLint64 *) = null_glGetInteger64v;
void (CODEGEN_FUNCPTR *_ptrc_glGetMultisamplefv)(GLenum, GLuint, GLfloat *) = null_glGetMultisamplefv;
void (CODEGEN_FUNCPTR *_ptrc_glGetSynciv)(GLsync, GLenum, GLsizei, GLsizei *, GLint *) = null_glGetSynciv;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsSync)(GLsync) = null_glIsSync;
void (CODEGEN_FUNCPTR *_ptrc_glMultiDrawElementsBaseVertex)(GLenum, const GLsizei *, GLenum, const GLvoid *const*, GLsizei, const GLint *) = null_glMultiDrawElementsBaseVertex;
void (CODEGEN_FUNCPTR *_ptrc_glProvokingVertex)(GLenum) = null_glProvokingVertex;
void (CODEGEN_FUNCPTR *_ptrc_glSampleMaski)(GLuint, GLbitfield) = null_glSampleMaski;
void (CODEGEN_FUNCPTR *_ptrc_glTexImage2DMultisample)(GLenum, GLsizei, GLint, GLsizei, GLsizei, GLboolean) = null_glTexImage2DMultisample;
void (CODEGEN_FUNCPTR *_ptrc_glTexImage3DMultisample)(GLenum, GLsizei, GLint, GLsizei, GLsizei, GLsizei, GLboolean) = null_glTexImage3DMultisample;
void (CODEGEN_FUNCPTR *_ptrc_glWaitSync)(GLsync, GLbitfield, GLuint64) = null_glWaitSync;
void (CODEGEN_FUNCPTR *_ptrc_glBindFragDataLocationIndexed)(GLuint, GLuint, GLuint, const GLchar *) = null_glBindFragDataLocationIndexed;
void (CODEGEN_FUNCPTR *_ptrc_glBindSampler)(GLuint, GLuint) = null_glBindSampler;
void (CODEGEN_FUNCPTR *_ptrc_glDeleteSamplers)(GLsizei, const GLuint *) = null_glDeleteSamplers;
void (CODEGEN_FUNCPTR *_ptrc_glGenSamplers)(GLsizei, GLuint *) = null_glGenSamplers;
GLint (CODEGEN_FUNCPTR *_ptrc_glGetFragDataIndex)(GLuint, const GLchar *) = null_glGetFragDataIndex;
void (CODEGEN_FUNCPTR *_ptrc_glGetQueryObjecti64v)(GLuint, GLenum, GLint64 *) = null_glGetQueryObjecti64v;
void (CODEGEN_FUNCPTR *_ptrc_glGetQueryObjectui64v)(GLuint, GLenum, GLuint64 *) = null_glGetQueryObjectui64v;
void (CODEGEN_FUNCPTR *_ptrc_glGetSamplerParameterIiv)(GLuint, GLenum, GLint *) = null_glGetSamplerParameterIiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetSamplerParameterIuiv)(GLuint, GLenum, GLuint *) = null_glGetSamplerParameterIuiv;
void (CODEGEN_FUNCPTR *_ptrc_glGetSamplerParameterfv)(GLuint, GLenum, GLfloat *) = null_glGetSamplerParameterfv;
void (CODEGEN_FUNCPTR *_ptrc_glGetSamplerParameteriv)(GLuint, GLenum, GLint *) = null_glGetSamplerParameteriv;
GLboolean (CODEGEN_FUNCPTR *_ptrc_glIsSampler)(GLuint) = null_glIsSampler;
void (CODEGEN_FUNCPTR *_ptrc_glQueryCounter)(GLuint, GLenum) = null_glQueryCounter;
void (CODEGEN_FUNCPTR *_ptrc_glSamplerParameterIiv)(GLuint, GLenum, const GLint *) = null_glSamplerParameterIiv;
void (CODEGEN_FUNCPTR *_ptrc_glSamplerParameterIuiv)(GLuint, GLenum, const GLuint *) = null_glSamplerParameterIuiv;
void (CODEGEN_FUNCPTR *_ptrc_glSamplerParameterf)(GLuint, GLenum, GLfloat) = null_glSamplerParameterf;
void (CODEGEN_FUNCPTR *_ptrc_glSamplerParameterfv)(GLuint, GLenum, const GLfloat *) = null_glSamplerParameterfv;
void (CODEGEN_FUNCPTR *_ptrc_glSamplerParameteri)(GLuint, GLenum, GLint) = null_glSamplerParameteri;
void (CODEGEN_FUNCPTR *_ptrc_glSamplerParameteriv)(GLuint, GLenum, const GLint *) = null_glSamplerParameteriv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribDivisor)(GLuint, GLuint) = null_glVertexAttribDivisor;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribP1ui)(GLuint, GLenum, GLboolean, GLuint) = null_glVertexAttribP1ui;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribP1uiv)(GLuint, GLenum, GLboolean, const GLuint *) = null_glVertexAttribP1uiv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribP2ui)(GLuint, GLenum, GLboolean, GLuint) = null_glVertexAttribP2ui;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribP2uiv)(GLuint, GLenum, GLboolean, const GLuint *) = null_glVertexAttribP2uiv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribP3ui)(GLuint, GLenum, GLboolean, GLuint) = null_glVertexAttribP3ui;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribP3uiv)(GLuint, GLenum, GLboolean, const GLuint *) = null_glVertexAttribP3uiv;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribP4ui)(GLuint, GLenum, GLboolean, GLuint) = null_glVertexAttribP4ui;
void (CODEGEN_FUNCPTR *_ptrc_glVertexAttribP4uiv)(GLuint, GLenum, GLboolean, const GLuint *) = null_glVertexAttribP4uiv;

int GLC_EXT_texture_compression_s3tc = 0;
int GLC_EXT_texture_sRGB = 0;
int GLC_EXT_texture_filter_anisotropic = 0;
int GLC_ARB_draw_elements_base_vertex = 0;
int GLC_ARB_vertex_array_object = 0;
int GLC_ARB_framebuffer_object = 0;
int GLC_ARB_half_float_pixel = 0;
int GLC_ARB_texture_float = 0;
int GLC_ARB_texture_rectangle = 0;
int GLC_ARB_multisample = 0;

int glcLoadFunctions(void) { return GLC_LOAD_SUCCEEDED; }
int glcGetMinorVersion(void) { return 0; }
int glcGetMajorVersion(void) { return 0; }
const GLubyte * glcErrorString(GLenum) { static const GLubyte s[] = "no error"; return s; }

} // extern "C"
