#!/usr/bin/env python3
"""
gen_glnull.py - generate server/glcore_null.cpp from VDrift's glcore.h.

The dedicated server links the same track/model/texture loading code as the
game, and that code calls GL through the function pointers glcore.h declares.
There is no GL on a server, so every pointer is bound to a stub that does
nothing and returns zero (or an empty string). Nothing on the server ever
renders; the stubs only keep the loaders happy.

    python tools/gen_glnull.py ../vdrift/src/graphics/glcore.h server/glcore_null.cpp
"""
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
decl = re.compile(r'^extern (.+?) \(CODEGEN_FUNCPTR \*_ptrc_(\w+)\)\((.*)\);$')
out = ['// Generated by tools/gen_glnull.py from glcore.h - do not edit.',
       '#include "graphics/glcore.h"', '', 'extern "C" {', '']
defs = []
for line in open(src, encoding='utf-8', errors='replace'):
    m = decl.match(line.strip())
    if not m:
        continue
    ret, name, args = m.group(1).strip(), m.group(2), m.group(3).strip()
    argl = 'void' if args in ('', 'void') else args
    if ret == 'void':
        body = ''
    elif ret == 'const GLubyte *':
        body = 'static const GLubyte s[] = ""; return s;'
    elif ret.endswith('*') or ret == 'GLsync':
        body = 'return 0;'
    elif name == 'glCheckFramebufferStatus':
        body = 'return 0x8CD5; /* GL_FRAMEBUFFER_COMPLETE */'
    elif name in ('glGetUniformLocation', 'glGetAttribLocation', 'glGetFragDataLocation'):
        body = 'return -1;'
    else:
        body = 'return 0;'
    out.append('static %s CODEGEN_FUNCPTR null_%s(%s) { %s }' % (ret, name, argl, body))
    defs.append('%s (CODEGEN_FUNCPTR *_ptrc_%s)(%s) = null_%s;' % (ret, name, argl, name))

out += [''] + defs + ['',
    'int GLC_EXT_texture_compression_s3tc = 0;',
    'int GLC_EXT_texture_sRGB = 0;',
    'int GLC_EXT_texture_filter_anisotropic = 0;',
    'int GLC_ARB_draw_elements_base_vertex = 0;',
    'int GLC_ARB_vertex_array_object = 0;',
    'int GLC_ARB_framebuffer_object = 0;',
    'int GLC_ARB_half_float_pixel = 0;',
    'int GLC_ARB_texture_float = 0;',
    'int GLC_ARB_texture_rectangle = 0;',
    'int GLC_ARB_multisample = 0;',
    '',
    'int glcLoadFunctions(void) { return GLC_LOAD_SUCCEEDED; }',
    'int glcGetMinorVersion(void) { return 0; }',
    'int glcGetMajorVersion(void) { return 0; }',
    'const GLubyte * glcErrorString(GLenum) { static const GLubyte s[] = "no error"; return s; }',
    '', '} // extern "C"', '']
open(dst, 'w', newline='\n').write('\n'.join(out))
print('%s: %d GL entry points stubbed' % (dst, len(defs)))
