# Generated from E:/vdrift/src/SConscript (desktop-only files removed; see src/android/*).
set(VDRIFT_GAME_SOURCES
    ${VD_SRC}/aabb.cpp
    ${VD_SRC}/aabbtree.cpp
    ${VD_SRC}/ai/ai_car_experimental.cpp
    ${VD_SRC}/ai/ai_car_standard.cpp
    ${VD_SRC}/ai/ai.cpp
    ${VD_SRC}/autoupdate.cpp
    ${VD_SRC}/bezier.cpp
    ${VD_SRC}/camera_chase.cpp
    ${VD_SRC}/camera_free.cpp
    ${VD_SRC}/camera_mount.cpp
    ${VD_SRC}/camera_orbit.cpp
    ${VD_SRC}/carcontrolmap.cpp
    ${VD_SRC}/cargraphics.cpp
    ${VD_SRC}/carsound.cpp
    ${VD_SRC}/cfg/config.cpp
    ${VD_SRC}/cfg/ptree.cpp
    ${VD_SRC}/cfg/ptree_inf.cpp
    ${VD_SRC}/cfg/ptree_ini.cpp
    ${VD_SRC}/containeralgorithm.cpp
    ${VD_SRC}/content/configfactory.cpp
    ${VD_SRC}/content/contentmanager.cpp
    ${VD_SRC}/content/modelfactory.cpp
    ${VD_SRC}/content/soundfactory.cpp
    ${VD_SRC}/content/texturefactory.cpp
    ${VD_SRC}/crashdetection.cpp
    ${VD_SRC}/downloadable.cpp
    ${VD_SRC}/dynamicsdraw.cpp
    ${VD_SRC}/fastmath.cpp
    ${VD_SRC}/game.cpp
    ${VD_SRC}/graphics/bcndecode.cpp
    ${VD_SRC}/graphics/dds.cpp
    ${VD_SRC}/graphics/drawable.cpp
    ${VD_SRC}/graphics/fbobject.cpp
    ${VD_SRC}/graphics/fbtexture.cpp
    ${VD_SRC}/graphics/glutil.cpp
    ${VD_SRC}/graphics/graphics_config_condition.cpp
    ${VD_SRC}/graphics/graphics_config.cpp
    ${VD_SRC}/graphics/graphics_gl2.cpp
    ${VD_SRC}/graphics/mesh_gen.cpp
    ${VD_SRC}/graphics/model.cpp
    ${VD_SRC}/graphics/model_joe03.cpp
    ${VD_SRC}/graphics/model_obj.cpp
    ${VD_SRC}/graphics/png.cpp
    ${VD_SRC}/graphics/render_input_postprocess.cpp
    ${VD_SRC}/graphics/render_input_scene.cpp
    ${VD_SRC}/graphics/render_output.cpp
    ${VD_SRC}/graphics/shader.cpp
    ${VD_SRC}/graphics/sky.cpp
    ${VD_SRC}/graphics/texture.cpp
    ${VD_SRC}/graphics/vertexarray.cpp
    ${VD_SRC}/graphics/vertexbuffer.cpp
    ${VD_SRC}/graphics/vertexformat.cpp
    ${VD_SRC}/gui/font.cpp
    ${VD_SRC}/gui/guicontrol.cpp
    ${VD_SRC}/gui/guicontrollist.cpp
    ${VD_SRC}/gui/gui.cpp
    ${VD_SRC}/gui/guiimage.cpp
    ${VD_SRC}/gui/guiimagelist.cpp
    ${VD_SRC}/gui/guilabel.cpp
    ${VD_SRC}/gui/guilabellist.cpp
    ${VD_SRC}/gui/guilanguage.cpp
    ${VD_SRC}/gui/guilinearslider.cpp
    ${VD_SRC}/gui/guioption.cpp
    ${VD_SRC}/gui/guipage.cpp
    ${VD_SRC}/gui/guiradialslider.cpp
    ${VD_SRC}/gui/guislider.cpp
    ${VD_SRC}/gui/guiwidget.cpp
    ${VD_SRC}/gui/guiwidgetlist.cpp
    ${VD_SRC}/gui/text_draw.cpp
    ${VD_SRC}/frustumcull.cpp
    ${VD_SRC}/joepack.cpp
    ${VD_SRC}/joeserialize.cpp
    ${VD_SRC}/k1999.cpp
    ${VD_SRC}/keyed_container.cpp
    ${VD_SRC}/linearinterp.cpp
    ${VD_SRC}/loadcamera.cpp
    ${VD_SRC}/loadcollisionshape.cpp
    ${VD_SRC}/loaddrawable.cpp
    ${VD_SRC}/main.cpp
    ${VD_SRC}/mathplane.cpp
    ${VD_SRC}/mathvector.cpp
    ${VD_SRC}/matrix4.cpp
    ${VD_SRC}/optional.cpp
    ${VD_SRC}/parallel_task.cpp
    ${VD_SRC}/particle.cpp
    ${VD_SRC}/pathmanager.cpp
    ${VD_SRC}/performance_testing.cpp
    ${VD_SRC}/physics/cardynamics.cpp
    ${VD_SRC}/physics/carengine.cpp
    ${VD_SRC}/physics/carsuspension.cpp
    ${VD_SRC}/physics/cartire1.cpp
    ${VD_SRC}/physics/cartire2.cpp
    ${VD_SRC}/physics/cartire3.cpp
    ${VD_SRC}/physics/dynamicsworld.cpp
    ${VD_SRC}/physics/fracturebody.cpp
    ${VD_SRC}/quaternion.cpp
    ${VD_SRC}/radix.cpp
    ${VD_SRC}/random.cpp
    ${VD_SRC}/replay.cpp
    ${VD_SRC}/reseatable_reference.cpp
    ${VD_SRC}/roadpatch.cpp
    ${VD_SRC}/roadstrip.cpp
    ${VD_SRC}/settings.cpp
    ${VD_SRC}/skidmarks.cpp
    ${VD_SRC}/sound/soundbuffer.cpp
    ${VD_SRC}/sound/sound.cpp
    ${VD_SRC}/sound/soundfilter.cpp
    ${VD_SRC}/sprite2d.cpp
    ${VD_SRC}/suspensionbumpdetection.cpp
    ${VD_SRC}/svn_sourceforge.cpp
    ${VD_SRC}/timer.cpp
    ${VD_SRC}/toggle.cpp
    ${VD_SRC}/track.cpp
    ${VD_SRC}/trackloader.cpp
    ${VD_SRC}/trackmap.cpp
    ${VD_SRC}/updatemanager.cpp
    ${VD_SRC}/utils.cpp
)
